#!/bin/sh

VERSION=3.47.0

APP_DIR="$( cd "$( dirname "$0" )" && pwd )"
FLUTTER_DIR="$APP_DIR/.flutter"

cd "$APP_DIR"

if [ ! -e "$FLUTTER_DIR" ]; then
    git clone "--filter=tree:0" https://github.com/flutter/flutter "$FLUTTER_DIR" --branch "$VERSION"

    "$FLUTTER_DIR"/bin/flutter config --no-analytics
fi

exec "$FLUTTER_DIR"/bin/flutter $@
