// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'known_hosts.freezed.dart';

class Host {
  final String hostname;
  final HostKeyType remoteKeyType;
  final String remoteHostKey;

  const Host({
    required this.hostname,
    required this.remoteKeyType,
    required this.remoteHostKey,
  });

  @override
  int get hashCode =>
      hostname.hashCode ^ remoteKeyType.hashCode ^ remoteHostKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Host &&
          runtimeType == other.runtimeType &&
          hostname == other.hostname &&
          remoteKeyType == other.remoteKeyType &&
          remoteHostKey == other.remoteHostKey;
}

enum HostKeyType {
  rsa,
  dss,
  ecdsa256,
  ecdsa384,
  ecdsa521,
  ed255219,
  ;
}

@freezed
class KnownHosts with _$KnownHosts {
  const factory KnownHosts({
    required List<Host> hosts,
  }) = _KnownHosts;
}
