use crate::node::{
    EnumNode, MethodNode, Node, NotificationNode, PrimitiveType, StructNode, TypeNode,
};

const PRELUDE: &str = r"
// This file is automatically generated. Do not edit manually.

// dart format off

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:uuid/uuid.dart';
import 'package:uuid/uuid_value.dart';

part 'generated.freezed.dart';
part 'generated.g.dart';

class UuidValueJsonConverter implements JsonConverter<UuidValue, String> {
  const UuidValueJsonConverter();

  @override
  UuidValue fromJson(String json) => UuidValue.fromString(json);

  @override
  String toJson(UuidValue object) => object.uuid;
}

class NullableUuidValueJsonConverter implements JsonConverter<UuidValue?, String?> {
  const NullableUuidValueJsonConverter();

  @override
  UuidValue? fromJson(String? json) => json == null ? null : UuidValue.fromString(json);

  @override
  String? toJson(UuidValue? object) => object?.uuid;
}

abstract class Serde<T> {
  SerdeFactory<T> get serde;
}

abstract class SerdeFactory<T> {
  dynamic serialize(T value);
  T deserialize(dynamic json);
}

abstract class Method<Result> {
  String getName();
}

abstract class Notification {
    String getName();
}

";

#[must_use]
pub fn render_dart(nodes: &[Node]) -> String {
    let mut output = Vec::new();
    output.push(PRELUDE.trim().to_owned());

    let type_names = collect_type_names(nodes);

    output.push(
        r"class SerdeRegistry {
  static final Map<Type, SerdeFactory<dynamic>> _registry = {"
            .into(),
    );
    for (is_struct, type_name) in type_names {
        output.push(format!("    {type_name}: const _{type_name}Serde(),"));
        if is_struct {
            output.push(format!("    _{type_name}: const _{type_name}Serde(),"));
        }
    }
    output.push(
        r"  };

  static void register<T>(SerdeFactory<T> factory) {
    _registry[T] = factory;
  }

  static SerdeFactory<T> get<T>() {
    final factory = _registry[T];
    if (factory == null) {
      throw Exception('No SerdeFactory registered for type $T');
    }
    return factory as SerdeFactory<T>;
  }

  static SerdeFactory<dynamic> getByType(Type type) {
    final factory = _registry[type];
    if (factory == null) {
      throw Exception('No SerdeFactory registered for type $type');
    }
    return factory;
  }
}
"
        .into(),
    );

    for node in nodes {
        match node {
            Node::Type(TypeNode::Struct(strukt)) => {
                output.push(render_struct(strukt, None));
            }
            Node::Type(TypeNode::Enum(enum_)) => {
                output.push(render_enum(enum_));
            }
            Node::Type(_) => {}
            Node::Method(method) => {
                if let TypeNode::Struct(params) = &method.params {
                    let params = StructNode {
                        name: method.name.clone(),
                        ..params.clone()
                    };
                    output.push(render_struct(&params, Some(Operation::Method(method))));
                } else if let Some(rendered) = render_type(&method.params) {
                    output.push(rendered);
                }
                if let Some(rendered) = render_type(&method.result) {
                    output.push(rendered);
                }
            }
            Node::Notification(notification) => {
                if let TypeNode::Struct(params) = &notification.params {
                    let params = StructNode {
                        name: notification.name.clone(),
                        ..params.clone()
                    };
                    output.push(render_struct(
                        &params,
                        Some(Operation::Notification(notification)),
                    ));
                } else if let Some(rendered) = render_type(&notification.params) {
                    output.push(rendered);
                }
            }
        }
        output.push(String::new());
    }

    output.push("// dart format on".to_owned());

    output.join("\n")
}

fn collect_type_names(nodes: &[Node]) -> Vec<(bool, String)> {
    fn add_name(
        is_struct: bool,
        name: &str,
        names: &mut Vec<(bool, String)>,
        seen: &mut std::collections::HashSet<(bool, String)>,
    ) {
        let entry = (is_struct, name.to_owned());
        if seen.insert(entry.clone()) {
            names.push(entry);
        }
    }

    fn collect_struct(
        strukt: &StructNode,
        name_override: Option<&str>,
        names: &mut Vec<(bool, String)>,
        seen: &mut std::collections::HashSet<(bool, String)>,
    ) {
        add_name(true, name_override.unwrap_or(&strukt.name), names, seen);
        for field in &strukt.fields {
            collect_type(&field.typ, names, seen);
        }
    }

    fn collect_type(
        type_node: &TypeNode,
        names: &mut Vec<(bool, String)>,
        seen: &mut std::collections::HashSet<(bool, String)>,
    ) {
        match type_node {
            TypeNode::Struct(strukt) => collect_struct(strukt, None, names, seen),
            TypeNode::Enum(enum_) => add_name(false, &enum_.name, names, seen),
            TypeNode::Array(inner) => collect_type(inner, names, seen),
            TypeNode::Primitive(_) | TypeNode::Reference(_) | TypeNode::Any | TypeNode::Unit => {}
        }
    }

    let mut names = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for node in nodes {
        match node {
            Node::Type(type_node) => collect_type(type_node, &mut names, &mut seen),
            Node::Method(method) => {
                if let TypeNode::Struct(params) = &method.params {
                    collect_struct(params, Some(&method.name), &mut names, &mut seen);
                } else {
                    collect_type(&method.params, &mut names, &mut seen);
                }
                collect_type(&method.result, &mut names, &mut seen);
            }
            Node::Notification(notification) => {
                if let TypeNode::Struct(params) = &notification.params {
                    collect_struct(params, Some(&notification.name), &mut names, &mut seen);
                } else {
                    collect_type(&notification.params, &mut names, &mut seen);
                }
            }
        }
    }
    names
}

#[derive(Clone, Copy)]
enum Operation<'a> {
    Method(&'a MethodNode),
    Notification(&'a NotificationNode),
}

fn render_type(this: &TypeNode) -> Option<String> {
    if let TypeNode::Struct(strukt) = &this {
        Some(render_struct(strukt, None))
    } else if let TypeNode::Enum(enum_) = &this {
        Some(render_enum(enum_))
    } else if let TypeNode::Array(array) = &this {
        render_type(array.as_ref())
    } else {
        None
    }
}

#[allow(clippy::too_many_lines)]
fn render_struct(this: &StructNode, operation: Option<Operation<'_>>) -> String {
    let mut lines = Vec::new();

    for field in &this.fields {
        if let Some(rendered) = render_type(&field.typ) {
            lines.push(rendered);
        }
    }

    for doc in &this.doc {
        if doc.is_empty() {
            lines.push("///".to_owned());
        } else {
            lines.push(format!("/// {doc}"));
        }
    }

    lines.push("@freezed".to_owned());
    match operation {
        Some(Operation::Method(method)) => lines.push(format!(
            "abstract class {} with _${} implements Serde<{}>, Method<{}> {{",
            this.name,
            this.name,
            this.name,
            render_type_node(&method.result)
        )),
        Some(Operation::Notification(_)) => lines.push(format!(
            "abstract class {} with _${} implements Serde<{}>, Notification {{",
            this.name, this.name, this.name
        )),
        None => lines.push(format!(
            "abstract class {} with _${} implements Serde<{}> {{",
            this.name, this.name, this.name
        )),
    }

    lines.push(format!("  const {}._();", this.name));
    lines.push(format!("  const factory {}(", this.name));

    if !this.fields.is_empty() {
        lines.push("    {".to_owned());
    }

    for field in &this.fields {
        if let Some(description) = &field.description {
            lines.push(format!("    /// {description}"));
        }

        let field_name = dart_field_name(&field.name);
        let json_name = field.name.clone();
        let field_type = render_type_node(&field.typ);
        let dart_type = if field.required {
            field_type.clone()
        } else {
            format!("{field_type}?")
        };
        let uuid_converter = match &field.typ {
            TypeNode::Primitive(PrimitiveType::Uuid) if field.required => {
                "    @UuidValueJsonConverter()".to_owned()
            }
            TypeNode::Primitive(PrimitiveType::Uuid) => {
                "    @NullableUuidValueJsonConverter()".to_owned()
            }
            _ => String::new(),
        };

        if !uuid_converter.is_empty() {
            lines.push(uuid_converter);
        }

        lines.push(format!(
            "    @JsonKey(name: '{json_name}') {}{dart_type} {field_name},",
            if field.required { "required " } else { "" }
        ));
    }
    if !this.fields.is_empty() {
        lines.push("    }".to_owned());
    }
    lines.push(format!("  ) = _{};", this.name));
    lines.push(format!(
        "  factory {}.fromJson(Map<String, dynamic> json) => _${}FromJson(json);",
        this.name, this.name
    ));

    lines.push(String::new());
    lines.push("  @override".to_owned());
    lines.push(format!(
        "  SerdeFactory<{}> get serde => const _{}Serde();",
        this.name, this.name
    ));

    let operation_name = match operation {
        Some(Operation::Method(method)) => Some(method.method_name.as_str()),
        Some(Operation::Notification(notification)) => Some(notification.method_name.as_str()),
        None => None,
    };
    if let Some(operation_name) = operation_name {
        lines.push(String::new());
        lines.push("  @override".to_owned());
        lines.push(format!("  String getName() => \"{operation_name}\";"));
    }
    lines.push("}".to_owned());
    lines.push(format!(
        r"// Implement methods of Serde<{name}> for {name}
class _{name}Serde implements SerdeFactory<{name}> {{
  const _{name}Serde();
  @override
  dynamic serialize({name} value) => value.toJson();

  @override
  {name} deserialize(dynamic json) => {name}.fromJson(json as Map<String, dynamic>);
}}",
        name = this.name
    ));
    lines.join("\n")
}

fn render_enum(this: &EnumNode) -> String {
    let mut lines = Vec::new();
    if let Some(description) = &this.description {
        lines.push(format!("/// {description}"));
    }

    lines.push("@JsonEnum(alwaysCreate: true)".to_owned());
    lines.push(format!(
        "enum {} implements Serde<{}> {{",
        this.name, this.name
    ));
    for (i, variant) in this.variants.iter().enumerate() {
        let value = variant.value.as_str();
        let json_value = if matches!(value, "true" | "false") {
            value.to_owned()
        } else {
            format!("'{value}'")
        };

        let variant_name = dart_variant_name(&variant.name);
        let description = variant.description.as_deref().unwrap_or(value);
        lines.push(format!("  /// {description}"));
        if i + 1 != this.variants.len() {
            lines.push(format!("  @JsonValue({json_value}) {variant_name},"));
            continue;
        }
        lines.push(format!("  @JsonValue({json_value}) {variant_name};"));
    }

    lines.push(String::new());
    lines.push(format!(
        "  dynamic toJson() => _${}EnumMap[this];",
        this.name
    ));
    lines.push(format!("  factory {}.fromJson(dynamic json) {{", this.name));
    lines.push(format!("    return _${}EnumMap.entries", this.name));
    lines.push("        .firstWhere(".to_owned());
    lines.push("          (entry) => entry.value == json,".to_owned());
    lines.push("          orElse: () => throw FormatException(".to_owned());
    lines.push(format!(
        "            \"Failed to deserialize '{}'. Value '$json' is invalid. \"",
        this.name
    ));
    lines.push(format!(
        "            \"Allowed values: {{_{}EnumMap.values.toList()}}\",",
        this.name
    ));
    lines.push("          ),".to_owned());
    lines.push("        )".to_owned());
    lines.push("        .key;".to_owned());
    lines.push("  }".to_owned());

    lines.push(String::new());
    lines.push("  @override".to_owned());
    lines.push(format!(
        "  SerdeFactory<{}> get serde => const _{}Serde();",
        this.name, this.name
    ));

    lines.push("}".to_owned());

    lines.push(format!(
        r"// Implement methods of Serde<{name}> for {name}
class _{name}Serde implements SerdeFactory<{name}> {{
  const _{name}Serde();
  @override
  dynamic serialize({name} value) => value.toJson();

  @override
  {name} deserialize(dynamic json) => {name}.fromJson(json);
}}",
        name = this.name,
    ));
    lines.join("\n")
}

fn render_type_node(type_node: &TypeNode) -> String {
    match type_node {
        TypeNode::Struct(node) => node.name.clone(),
        TypeNode::Enum(node) => node.name.clone(),
        TypeNode::Primitive(PrimitiveType::String) => "String".to_owned(),
        TypeNode::Primitive(PrimitiveType::Uuid) => "UuidValue".to_owned(),
        TypeNode::Primitive(PrimitiveType::Integer) => "int".to_owned(),
        TypeNode::Primitive(PrimitiveType::Number) => "double".to_owned(),
        TypeNode::Primitive(PrimitiveType::Boolean) => "bool".to_owned(),
        TypeNode::Array(inner) => format!("List<{}>", render_type_node(inner)),
        TypeNode::Reference(name) => name.clone(),
        TypeNode::Any => "Map<String, dynamic>".to_owned(),
        TypeNode::Unit => "Object?".to_owned(),
    }
}

fn dart_field_name(name: &str) -> String {
    let mut parts = Vec::new();
    let mut current = String::new();

    for ch in name.chars() {
        if matches!(ch, '-' | '_' | ' ' | '.' | '/' | ':') {
            if !current.is_empty() {
                parts.push(current);
                current = String::new();
            }
            continue;
        }

        if ch.is_ascii_uppercase() && !current.is_empty() {
            let prev = current.chars().last().unwrap_or_default();
            if prev.is_ascii_lowercase() || prev.is_ascii_digit() {
                parts.push(current);
                current = String::new();
            }
        }

        current.push(ch);
    }

    if !current.is_empty() {
        parts.push(current);
    }

    if parts.is_empty() {
        return "value".to_owned();
    }

    let mut out = String::new();
    for (index, part) in parts.iter().enumerate() {
        let normalized = part.trim();
        if normalized.is_empty() {
            continue;
        }

        let mut chars = normalized.chars();
        let first = chars.next().unwrap_or_default();
        let rest = chars.as_str();

        if index == 0 {
            out.push(first.to_ascii_lowercase());
            out.push_str(&rest.to_ascii_lowercase());
        } else {
            out.push(first.to_ascii_uppercase());
            out.push_str(&rest.to_ascii_lowercase());
        }
    }

    if out.is_empty() {
        return "value".to_owned();
    }

    match out.as_str() {
        "class" | "enum" | "void" | "new" | "default" | "return" | "const" => {
            format!("{out}_")
        }
        _ => out,
    }
}

fn dart_variant_name(name: &str) -> String {
    let out = dart_field_name(name);
    match out.as_str() {
        "class" | "enum" | "void" | "new" | "default" | "return" | "const" => {
            format!("{out}_")
        }
        _ => out,
    }
}
