use std::fmt::Write;

use crate::node::{
    EnumNode, MethodNode, Node, NotificationNode, PrimitiveType, StructNode, TypeNode, TypeRef,
};

#[must_use]
pub fn render_rust(nodes: &[Node]) -> String {
    let mut output = Vec::new();
    output.push("// This file is automatically generated. Do not edit manually.".to_owned());
    output.push(String::new());

    for node in nodes {
        match node {
            Node::Type(TypeNode::Struct(node)) => output.push(render_struct(node)),
            Node::Type(TypeNode::Enum(node)) => output.push(render_enum(node)),
            Node::Type(TypeNode::Ref(_)) => {}
            Node::Method(node) => output.push(render_method(node)),
            Node::Notification(node) => output.push(render_notification(node)),
        }
    }

    output.join("\n")
}

fn render_struct(this: &StructNode) -> String {
    let mut lines = Vec::new();
    for doc in &this.doc {
        lines.push(format!("/// {doc}"));
    }
    lines.push("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]".to_owned());
    lines.push("#[serde(rename_all = \"kebab-case\")]".to_owned());
    lines.push("#[allow(missing_copy_implementations)]".to_owned());
    lines.push(format!("pub struct {} {{", this.name));

    for field in &this.fields {
        if let Some(description) = &field.description {
            lines.push(format!("    /// {description}"));
        }

        let rust_name = rust_field_name(&field.name);
        let field_type = render_type_ref(&field.type_ref);
        if field.required {
            lines.push(format!("    pub {rust_name}: {field_type},"));
        } else {
            lines.push(format!(
                "    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n    pub {rust_name}: Option<{field_type}>,"
            ));
        }
    }

    lines.push("}\n".to_owned());
    lines.join("\n")
}

fn render_enum(this: &EnumNode) -> String {
    let mut lines = Vec::new();
    if let Some(description) = &this.description {
        lines.push(format!("/// {description}"));
    }
    lines.push(
        "#[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize, PartialEq, Eq)]"
            .to_owned(),
    );
    lines.push(format!("pub enum {} {{", this.name));
    for variant in &this.variants {
        lines.push(format!(
            "    #[serde(rename = \"{}\")]\n    {},",
            variant.value, variant.name
        ));
    }
    lines.push("}\n".to_owned());
    lines.join("\n")
}

fn render_method(this: &MethodNode) -> String {
    format!(
        "impl Method for {} {{\n    const NAME: &'static str = \"{}\";\n    type Result = {};\n}}\n",
        this.name,
        this.method_name,
        render_type_node(&this.result)
    )
}

fn render_notification(this: &NotificationNode) -> String {
    let mut lines = String::new();

    writeln!(lines, "impl {} {{", this.name).unwrap();
    writeln!(
        lines,
        "    pub const NAME: &'static str = \"{}\";",
        this.method_name
    )
    .unwrap();
    writeln!(lines, "}}").unwrap();

    lines.push('\n');

    writeln!(lines, "impl Notification for {} {{", this.name).unwrap();
    writeln!(lines, "    fn name(&self) -> &'static str {{").unwrap();
    writeln!(lines, "        \"{}\"", this.method_name).unwrap();
    writeln!(lines, "    }}").unwrap();
    writeln!(lines, "    fn to_value(&self) -> Value {{").unwrap();
    writeln!(
        lines,
        "        let value = serde_json::to_value(self).expect(\"Failed to serialize to JSON\");"
    )
    .unwrap();
    writeln!(
        lines,
        "        serde_json::from_value(value).expect(\"Failed to deserialize from JSON\")"
    )
    .unwrap();
    writeln!(lines, "    }}").unwrap();
    writeln!(lines, "    fn from_value(value: Value) -> Result<Self>").unwrap();
    writeln!(lines, "    where").unwrap();
    writeln!(lines, "        Self: Sized,").unwrap();
    writeln!(lines, "    {{").unwrap();
    writeln!(lines, "        let value = serde_json::to_value(value)?;").unwrap();
    writeln!(lines, "        Ok(serde_json::from_value(value)?)").unwrap();
    writeln!(lines, "    }}").unwrap();
    writeln!(lines, "}}").unwrap();
    lines
}

fn render_type_node(type_node: &TypeNode) -> String {
    match type_node {
        TypeNode::Struct(node) => node.name.clone(),
        TypeNode::Enum(node) => node.name.clone(),
        TypeNode::Ref(type_ref) => render_type_ref(type_ref),
    }
}

fn render_type_ref(type_ref: &TypeRef) -> String {
    match type_ref {
        TypeRef::Primitive(PrimitiveType::String) => "Box<str>".to_owned(),
        TypeRef::Primitive(PrimitiveType::Uuid) => "uuid::Uuid".to_owned(),
        TypeRef::Primitive(PrimitiveType::Integer) => "i64".to_owned(),
        TypeRef::Primitive(PrimitiveType::Number) => "f64".to_owned(),
        TypeRef::Primitive(PrimitiveType::Boolean) => "bool".to_owned(),
        TypeRef::Array(inner) => format!("Vec<{}>", render_type_ref(inner)),
        TypeRef::Map(inner) => format!(
            "std::collections::HashMap<Box<str>, {}>",
            render_type_ref(inner)
        ),
        TypeRef::Object(name) | TypeRef::Enum(name) | TypeRef::Reference(name) => name.clone(),
        TypeRef::Json => "Value".to_owned(),
        TypeRef::Unit => "()".to_owned(),
    }
}

fn rust_field_name(name: &str) -> String {
    let mut result = String::new();
    let mut prev_was_separator = false;

    for ch in name.chars() {
        if matches!(ch, '-' | '_' | ' ' | '.' | '/' | ':') {
            if !result.is_empty() && !prev_was_separator {
                result.push('_');
                prev_was_separator = true;
            }
            continue;
        }

        if ch.is_ascii_uppercase() && !result.is_empty() && !prev_was_separator {
            let last = result.chars().last().unwrap_or_default();
            if last.is_ascii_lowercase() || last.is_ascii_digit() {
                result.push('_');
            }
        }

        result.push(ch.to_ascii_lowercase());
        prev_was_separator = false;
    }

    while result.starts_with('_') {
        result.remove(0);
    }
    while result.ends_with('_') {
        result.pop();
    }

    if result.is_empty() {
        return "value".to_owned();
    }

    match result.as_str() {
        "type" => "r#type".to_owned(),
        "self" => "self_".to_owned(),
        _ => result,
    }
}
