[package]
name = "stride_api"
description = "Stride's database"
keywords = ["stride", "wasm", "plugin"]
categories = []
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

build = "build.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true

uuid.workspace = true
indexmap = { workspace = true, features = ["serde"] }

[build-dependencies]
stride_api_codegen.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
