// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: avoid_dynamic_calls
// ignore_for_file: avoid_equals_and_hash_code_on_mutable_classes
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: inference_failure_on_instance_creation

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:stride/bridge/api/error.dart';
import 'package:stride/bridge/frb_generated.dart';

part 'background.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BgTask`, `BridgeHook`, `Method`, `RepositorySpec`, `State`, `TaskSync`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `on_task_result`, `on_task_start`

Stream<BackgroundResult> init() =>
    RustLib.instance.api.crateApiBackgroundInit();

Future<void> execute({required String task}) =>
    RustLib.instance.api.crateApiBackgroundExecute(task: task);

@freezed
sealed class BackgroundResult with _$BackgroundResult {
  const BackgroundResult._();

  const factory BackgroundResult.start({required String task}) =
      BackgroundResult_Start;
  const factory BackgroundResult.done({
    required String task,
    required bool success,
  }) = BackgroundResult_Done;
  const factory BackgroundResult.error({
    required String task,
    required RustError error,
  }) = BackgroundResult_Error;
}
