// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: avoid_dynamic_calls
// ignore_for_file: avoid_equals_and_hash_code_on_mutable_classes
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: inference_failure_on_instance_creation

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:stride/bridge/api/error.dart';
import 'package:stride/bridge/frb_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FlutterContext`, `PromptSelectHandler`, `PromptTest`, `TaskSyncHandler`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `actions`, `clone`, `execute`, `fmt`, `fmt`, `fmt`, `handle`, `handle`, `input`, `name`, `notify`, `summary`

Stream<String> createContext() =>
    RustLib.instance.api.crateApiContextCreateContext();

Future<void> execute({required String method, required String args}) =>
    RustLib.instance.api.crateApiContextExecute(method: method, args: args);
