// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:stride/bridge/api/error.dart';
import 'package:stride/bridge/api/filter.dart';
import 'package:stride/bridge/frb_generated.dart';
import 'package:stride/bridge/task.dart';
import 'package:stride/bridge/task/annotation.dart';
import 'package:uuid/uuid.dart';

abstract class StrideRepository {
  Future<void> add({required Task task});

  Future<bool> changeCategory({required Task task, required TaskStatus status});

  Future<void> clear();

  Future<String> export_();

  Future<void> import_({required String content});

  Future<bool> removeByTask({required Task task});

  Future<Task?> removeByUuid({required UuidValue uuid});

  Future<void> sync_();

  Future<Task?> taskByUuid({required UuidValue uuid});

  Future<List<Task>> tasksWithFilter({required Filter filter});

  Future<void> unload();

  Future<bool> update({required Task task});
}

abstract class StrideRepositoryExt {
  Future<List<Task>> tasks();
}
