// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../task.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'filter.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `default`, `fmt`, `fmt`

@freezed
class Filter with _$Filter {
  const factory Filter({
    required UuidValue uuid,
    required String name,
    required Set<TaskStatus> status,
    required String search,
  }) = _Filter;
}

@freezed
sealed class FilterSelection with _$FilterSelection {
  const FilterSelection._();

  const factory FilterSelection.predefined({
    required UuidValue uuid,
  }) = FilterSelection_Predefined;
  const factory FilterSelection.temporary({
    required Filter filter,
  }) = FilterSelection_Temporary;
}
