#![forbid(missing_docs)]

//! This module defines the command line arguments for the `stride` CLI.

use std::{path::PathBuf, str::FromStr};

use clap::{Parser, Subcommand, ValueEnum};
use uuid::Uuid;

#[derive(Parser, Debug)]
#[clap(author, version, about, long_about = None)]
#[allow(clippy::module_name_repetitions)]
/// An command line interface for stride
pub struct CliArgs {
    /// Task ID to perform the opteration.
    pub task_id: Option<String>,

    #[command(subcommand)]
    /// The mode to operate in
    pub mode: Option<Mode>,

    /// Print incoming logs to stdout.
    #[clap(long, default_value_t = false)]
    pub print_logs: bool,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
/// The possible backend Repository types
pub enum Backend {
    /// A `git` based repository, which tracks changes as commits
    Git,

    /// A `taskchampion` Replica, which can sync to `taskwarrior`
    TaskChampion,
}

/// Represents a discrete modification, attribute alteration, or metadata update for a task.
///
/// `TaskModifier` variants are typically generated by parsing individual space-separated command-line tokens
/// (e.g., using Taskwarrior-style `key:value` syntax or prefix symbols). They allow users to change
/// task properties like due dates, priorities, or tags alongside free-form text.
#[derive(Debug, Clone)]
pub enum TaskModifier {
    /// A deadline requirement for the task.
    Due(String),

    /// A severity or order weighting for the task.
    Priority(String),

    /// An explicit tag to be attached to the task metadata.
    TagAdd(String),

    /// An explicit tag to be stripped from the task metadata.
    TagRemove(String),

    /// Free-form description updates or fallback query terms.
    ///
    /// Captures any token that does not match known key-value signatures or symbol prefixes.
    Text(String), // Fallback text modification
}

// Implement string parsing for Taskwarrior-style key:value syntax
impl FromStr for TaskModifier {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if let Some(date) = s.strip_prefix("due:") {
            Ok(TaskModifier::Due(date.to_string()))
        } else if let Some(pri) = s.strip_prefix("priority:") {
            Ok(TaskModifier::Priority(pri.to_string()))
        } else if let Some(pri) = s.strip_prefix("pri:") {
            Ok(TaskModifier::Priority(pri.to_string()))
        } else if let Some(tag) = s.strip_prefix("+") {
            Ok(TaskModifier::TagAdd(tag.to_string()))
        } else if let Some(tag) = s.strip_prefix("-") {
            Ok(TaskModifier::TagRemove(tag.to_string()))
        } else {
            Ok(TaskModifier::Text(s.to_string()))
        }
    }
}

#[derive(Debug, Subcommand)]
/// The Modus of operation
pub enum Mode {
    /// Find all task matching the filter
    Search {
        /// A string (or optionally multiple strings concatenated with a space) to search for in the
        /// task list.
        filter: Vec<String>,
    },

    /// Add a task to the storage
    Add {
        /// A description of the task.
        /// If this is equal to '-' we try to read it from `stdin`.
        content: Vec<String>,
    },

    /// Complete the task.
    Done {
        /// ID of the task to complete.
        id: String,
    },

    /// Modify a task
    #[command(visible_alias = "mod")]
    Modify {
        /// Collects modifiers like 'due:2026-10-12' or 'text context'
        #[arg(value_parser = clap::value_parser!(TaskModifier), allow_hyphen_values = true)]
        modifiers: Vec<TaskModifier>,
    },

    /// Undo previous change.
    Undo {
        /// Undo `count` changes.
        count: Option<usize>,
    },

    /// Sync the task storage
    Sync {
        /// Choose backend to sync.
        backend: Option<String>,
    },

    /// Output the git-log of the task storage
    Log {
        /// The number of items to display
        #[arg(default_value_t = u32::MAX)]
        limit: u32,

        /// The number of items to skip
        skip: Option<u32>,
    },

    /// Export the task storage in a task format
    Export {
        /// The output file path. Otherwise will write to `stdout`.
        filepath: Option<PathBuf>,
    },

    /// Import previously `export`ed tasks.
    Import {
        /// The file path to read from. Otherwise will try to read from `stdin`.
        filepath: Option<PathBuf>,
    },

    /// Change repository.
    Repository {
        /// The UUID of the repository.
        uuid: Uuid,
    },

    /// Manage backends.
    Backend {
        /// Backend command to apply.
        #[command(subcommand)]
        command: Option<BackendCommand>,
    },

    /// Manage plugins.
    Plugin {
        /// Plugin command to apply.
        #[command(subcommand)]
        command: Option<PluginCommand>,
    },

    /// Manage SSH options.
    Ssh {
        /// SSH command to apply.
        #[command(subcommand)]
        command: SshCommand,
    },
}

/// Backend command/action to apply.
#[derive(Debug, Clone, Subcommand)]
pub enum BackendCommand {
    /// list backends
    List,
    /// Create a new backend.
    New {
        /// The name of the backend to be created.
        backend_name: String,
    },
    /// Remove a backend backend.
    Remove {
        /// The name of the backend to be removed.
        backend_name: String,
    },
    /// Configure a backend option.
    Config {
        /// Name of backend to configure.
        backend_name: String,

        /// Property name.
        property_name: Option<String>,

        /// Unset a property.
        #[clap(long, conflicts_with = "property_value")]
        unset: bool,

        /// Property name.
        property_value: Option<String>,
    },
}

/// Plugin command/action to apply.
#[derive(Debug, Clone, Subcommand)]
pub enum PluginCommand {
    /// Import plugin.
    Import {
        /// Filepath to the .zip plugin archive.
        filepath: PathBuf,
    },
    /// Enable/Disable plugin.
    Toggle {
        /// Plugin to toggle.
        plugin_name: String,
    },
}

/// SSH command/action to apply.
#[derive(Debug, Clone, Subcommand)]
pub enum SshCommand {
    /// Manage SSH keys.
    Key {
        /// SSH Key command to apply.
        #[command(subcommand)]
        command: Option<SshKeyCommand>,
    },

    /// Manage SSH known hosts.
    KnownHosts {
        /// SSH Known host command to apply.
        #[command(subcommand)]
        command: Option<SshKnownHostsCommand>,
    },
}

/// SSH command/action to apply.
#[derive(Debug, Clone, Copy, Subcommand)]
pub enum SshKeyCommand {
    /// Generate new SSH key.
    Generate,

    /// Remove a SSH key.
    Remove {
        /// ID of the SSH key to be removed.
        id: Uuid,
    },
}

/// SSH Known host command to apply.
#[derive(Debug, Clone, Subcommand)]
pub enum SshKnownHostsCommand {
    /// Remove a SSH known host.
    Remove {
        /// A Host name (e.g. `github.com`).
        hostname: String,
    },
}
